### ISSUE TITLE
LOVE THIS!

### ISSUE THREAD

**Issue by sdhutchins** [dmulholl/janus-python#1]
@dmulholland 
I've been looking for something like this for a long time!!!!!

Quick note, would be great to put the link to the example in your readme because I looked everywhere until it hit me smack in the face. 😆 Also, the link to your site is blocked for me (hospital/research wing). However, I noticed it was the http version. The https version works fine.  I just thought to mention that.

https://mulholland.xyz/docs/janus/

**Comment by dmulholl** [comment]
Thanks :) Glad you like it!

And thanks for the feedback - that's really useful. I've added links to the sample application in the readme and documentation. 

I have no idea why the site is being blocked, that's really odd. I wonder is the filter trying to block all .xyz domains? I've updated the links to use the https version, which I probably should have been doing anyway! Thanks for the heads up.
